version: "3"
services:
  flask:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    working_dir: /src/backend
    command: python server.py

  react:
    image: node:14.15-buster
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    working_dir: /src/frontend/app
    command: yarn start
