version: "3"
services:
  flask:
    build:
      context: backend
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"

  react:
    image: node:14.15-buster
    volumes:
      - .:/src
    command: /bin/sh -c "while sleep 1000; do :; done"
