version: "3"
services:
  flask:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - base-variables.env
      - flask-variables.env
    volumes:
      - .:/src
    ports:
      - "5000:5000"
    working_dir: /src/backend
    command: python app/server.py

  react:
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - base-variables.env
      - react-variables.env
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    working_dir: /src/frontend/app
    command: yarn start

  mock:
    image: stoplight/prism
    ports:
      - "4010:4010"
    command: mock -h 0.0.0.0 -d https://raw.githack.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore-expanded.yaml

  dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -dbPath . -sharedDb
